import 'package:flutter/material.dart';
import 'package:myapp_core/common/themes.dart';
import 'package:ldp/model/user_view_model.dart';

// import 'database/check_db_connection.dart';
// import 'database/check_st_connection.dart';
import 'ldp_screen.dart';

// void main() => runApp(MyApp());
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ldp Demo',
      theme: buildMyAppTheme(context),
      home: LdpScreen(
          userViewModel: UserViewModel(username: "admin", password: "00000"),
          isFromUser: true,
          // listingID: "-MM8ch1xNLcAwgeVKdHc"),  // generated by us
          listingID: "-MLkrcZq4IO766ZEF9pX"), // pineapple listing
      // listingID: "-MLkrc_7YlHo5gjmTHS0"),     // no image listing
      // home: CheckDataBaseConnection()
      // home: CheckStorageConnection()
    );
  }
}
